### ISSUE TITLE
Failed tests with PHP  7.0

### ISSUE THREAD

**Issue by remicollet** [hprose/hprose-pecl#1]
```
 + /opt/remi/php70/root/usr/bin/php -n run-tests.php --show-diff
 =====================================================================
 PHP         : /opt/remi/php70/root/usr/bin/php 
 PHP_SAPI    : cli
 PHP_VERSION : 7.0.0-dev
 ZEND_VERSION: 3.0.0-dev
 PHP_OS      : Linux - Linux schrodingerscat.famillecollet.com 3.19.3-200.fc21.x86_64 #1 SMP Thu Mar 26 21:39:42 UTC 2015 x86_64
 INI actual  : /builddir/build/BUILD/php70-php-pecl-hprose-1.0.0/NTS
 More .INIs  :  
 CWD         : /builddir/build/BUILD/php70-php-pecl-hprose-1.0.0/NTS
 Extra dirs  : 
 VALGRIND    : Not used
 =====================================================================
 TIME START 2015-04-02 07:41:03
 =====================================================================
 TEST 1/8 [tests/bytes_io.phpt]
 PASS Test that the Hprose\BytesIO class works. [tests/bytes_io.phpt] 
 TEST 2/8 [tests/class_manager.phpt]
 PASS Test that the Hprose\ClassManager class works. [tests/class_manager.phpt] 
 TEST 3/8 [tests/formatter.phpt]
 ========DIFF========
 014+ 
 015+ Termsig=11
 ========DONE========
 FAIL Test that the Hprose\Formatter class works. [tests/formatter.phpt] 
 TEST 4/8 [tests/raw_reader.phpt]
 ========DIFF========
 036+ 
 037+ Termsig=6
 ========DONE========
 FAIL Test that the Hprose\RawReader class works. [tests/raw_reader.phpt] 
 TEST 5/8 [tests/reader.phpt]
 ========DIFF========
 096+ Termsig=11
 ========DONE========
 FAIL Test that the Hprose\Reader class works. [tests/reader.phpt] 
 TEST 6/8 [tests/result_mode.phpt]
 PASS Test that the Hprose\ResultMode class works. [tests/result_mode.phpt] 
 TEST 7/8 [tests/tags.phpt]
 PASS Test that the Hprose\Tags class works. [tests/tags.phpt] 
 TEST 8/8 [tests/writer.phpt]
 ========DIFF========
 004+ 
 005+ Termsig=11
 ========DONE========
 FAIL Test that the Hprose\Writer class works. [tests/writer.phpt] 
 =====================================================================
 TIME END 2015-04-02 07:41:05
 =====================================================================
 TEST RESULT SUMMARY
 ---------------------------------------------------------------------
 Exts skipped    :    0
 Exts tested     :   17
 ---------------------------------------------------------------------
 Number of tests :    8                 8
 Tests skipped   :    0 (  0.0%) --------
 Tests warned    :    0 (  0.0%) (  0.0%)
 Tests failed    :    4 ( 50.0%) ( 50.0%)
 Expected fail   :    0 (  0.0%) (  0.0%)
 Tests passed    :    4 ( 50.0%) ( 50.0%)
 ---------------------------------------------------------------------
 Time taken      :    2 seconds
 =====================================================================
 =====================================================================
 FAILED TEST SUMMARY
 ---------------------------------------------------------------------
 Test that the Hprose\Formatter class works. [tests/formatter.phpt]
 Test that the Hprose\RawReader class works. [tests/raw_reader.phpt]
 Test that the Hprose\Reader class works. [tests/reader.phpt]
 Test that the Hprose\Writer class works. [tests/writer.phpt]
 =====================================================================
```

**Comment by andot** [comment]
Thank you, I will check it.

**Comment by andot** [comment]
I test it pass on travis-ci with PHP 7.
https://travis-ci.org/hprose/hprose-pecl/jobs/56865506
And I test it pass on my Mac OS X and Ubuntu x64 with PHP 7 of the master branch of https://github.com/php/php-src, too.

What can I do...

**Comment by remicollet** [comment]
Segfaults occurs with latest snapshot of 7.0.0-dev.

```
 #0  zend_llist_destroy (l=0x7ffff3a565b0) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_llist.c:109
 #1  0x00007fffd83fbb7d in hprose_real_writer_refer_free (_this=0x7ffff3a86230) at /work/GIT/hprose-pecl/include/hprose_writer.h:139
 #2  0x00007fffd83fbb3d in hprose_writer_destroy (_this=0x7ffff3a87760) at /work/GIT/hprose-pecl/include/hprose_writer.h:217
 #3  hprose_writer_free (_this=0x7ffff3a87760) at /work/GIT/hprose-pecl/include/hprose_writer.h:222
 #4  zim_hprose_writer___destruct (execute_data=<optimized out>, return_value=<optimized out>) at /work/GIT/hprose-pecl/src/hprose_writer.c:35
 #5  0x00005555557889fa in dtrace_execute_internal (execute_data=<optimized out>, return_value=<optimized out>)
     at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_dtrace.c:102
 #6  0x000055555578a913 in zend_call_function (fci=fci@entry=0x7fffffffb560, fci_cache=<optimized out>, fci_cache@entry=0x7fffffffb530)
     at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_execute_API.c:880
 #7  0x00005555557b772e in zend_call_method (object=object@entry=0x7fffffffb620, obj_ce=<optimized out>, fn_proxy=fn_proxy@entry=0x7fffffffb618, 
     function_name=function_name@entry=0x5555558870d7 "__destruct", function_name_len=function_name_len@entry=10, retval_ptr=retval_ptr@entry=0x0, param_count=0, arg1=0x0, arg2=0x0)
     at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_interfaces.c:101
 #8  0x00005555557d2690 in zend_objects_destroy_object (object=<optimized out>) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_objects.c:126
 #9  0x00005555557d794c in zend_objects_store_del (object=0x7ffff3a5c578) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_objects_API.c:163
 #10 0x00005555557acb8a in _zend_hash_del_el_ex (prev=<optimized out>, p=0x7ffff3a57200, idx=8, ht=0x555555b8f3b0 <executor_globals+304>)
     at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_hash.c:899
 #11 _zend_hash_del_el (p=0x7ffff3a57200, idx=8, ht=0x555555b8f3b0 <executor_globals+304>) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_hash.c:923
 #12 zend_hash_reverse_apply (ht=ht@entry=0x555555b8f3b0 <executor_globals+304>, apply_func=apply_func@entry=0x555555788b30 <zval_call_destructor>)
     at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_hash.c:1438
 #13 0x0000555555788ea5 in shutdown_destructors () at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend_execute_API.c:224
 #14 0x00005555557987c7 in zend_call_destructors () at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/Zend/zend.c:909
 #15 0x000055555573a9b5 in php_request_shutdown (dummy=<optimized out>) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/main/main.c:1750
 #16 0x0000555555834a82 in do_cli (argc=4, argv=0x555555b94c10) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/sapi/cli/php_cli.c:1135
 #17 0x000055555561b022 in main (argc=4, argv=0x555555b94c10) at /usr/src/debug/php-src-83a15801cc8619a1a83307e573bf1b63f0d4b53c/sapi/cli/php_cli.c:1334
```

Notice, RPM build use some "hardening" options, can you try with them ?

```
 export CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic"
 export LDFLAGS="-Wl,-z,relro"
```

**Comment by andot** [comment]
Thank you!

**Comment by andot** [comment]
I have tried that options, but configure can't run with that options in ubuntu. Now, I changed something and fixed something. Could you help me try again on the last master branch.

**Comment by remicollet** [comment]
Which option is not known ? (perhaps a too old gcc version)

**Comment by andot** [comment]
When I set this:

```
 export CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic"
```

run configure:

```
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... no
configure: error: in `/mnt/hgfs/Work/Git/hprose-pecl':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

The following is the config.log:

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by configure, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = kylin
uname -m = x86_64
uname -r = 3.13.0-48-generic
uname -s = Linux
uname -v = #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/andot/.phpenv/shims
PATH: /home/andot/.phpenv/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /usr/games
PATH: /usr/local/games
PATH: /usr/lib/jvm/java-8-oracle/bin
PATH: /usr/lib/jvm/java-8-oracle/db/bin
PATH: /usr/lib/jvm/java-8-oracle/jre/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2294: checking for grep that handles long lines and -e
configure:2352: result: /bin/grep
configure:2357: checking for egrep
configure:2419: result: /bin/grep -E
configure:2424: checking for a sed that does not truncate output
configure:2478: result: /bin/sed
configure:2610: checking for cc
configure:2626: found /usr/bin/cc
configure:2637: result: cc
configure:2668: checking for C compiler version
configure:2677: cc --version >&5
cc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2688: $? = 0
configure:2677: cc -v >&5
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
configure:2688: $? = 0
configure:2677: cc -V >&5
cc: error: unrecognized command line option '-V'
cc: fatal error: no input files
compilation terminated.
configure:2688: $? = 4
configure:2677: cc -qversion >&5
cc: error: unrecognized command line option '-qversion'
cc: fatal error: no input files
compilation terminated.
configure:2688: $? = 4
configure:2708: checking whether the C compiler works
configure:2730: cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic   conftest.c  >&5
cc: error: unrecognized command line option '-fstack-protector-strong'
configure:2734: $? = 1
configure:2772: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2777: error: in `/mnt/hgfs/Work/Git/hprose-pecl':
configure:2779: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_EGREP='/bin/grep -E'
ac_cv_path_GREP=/bin/grep
ac_cv_prog_ac_ct_CC=cc
lt_cv_path_SED=/bin/sed

## ----------------- ##
## Output variables. ##
## ----------------- ##

AR=''
AWK=''
CC='cc'
CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic'
CONFIGURE_COMMAND=' '\''./configure'\''  '\''CFLAGS=-O2 '\''-g'\'' '\''-pipe'\'' '\''-Wall'\'' '\''-Werror=format-security'\'' '\''-Wp,-D_FORTIFY_SOURCE=2'\'' '\''-fexceptions'\'' '\''-fstack-protector-strong'\'' '\''--param=ssp-buffer-size=4'\'' '\''-grecord-gcc-switches'\'' '\''-m64'\'' '\''-mtune=generic'\'''\'''
CONFIGURE_OPTIONS=' '\''CFLAGS=-O2 '\''-g'\'' '\''-pipe'\'' '\''-Wall'\'' '\''-Werror=format-security'\'' '\''-Wp,-D_FORTIFY_SOURCE=2'\'' '\''-fexceptions'\'' '\''-fstack-protector-strong'\'' '\''--param=ssp-buffer-size=4'\'' '\''-grecord-gcc-switches'\'' '\''-m64'\'' '\''-mtune=generic'\'''\'''
CPP=''
CPPFLAGS=''
DEFS=''
DSYMUTIL=''
ECHO='echo'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/bin/grep -E'
EXEEXT=''
GREP='/bin/grep'
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LN_S=''
LTLIBOBJS=''
NMEDIT=''
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
RANLIB=''
RE2C=''
SED='/bin/sed'
SHELL='/bin/bash'
SHLIB_DL_SUFFIX_NAME=''
SHLIB_SUFFIX_NAME=''
STRIP=''
ac_ct_CC='cc'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE}'
dvidir='${docdir}'
exec_prefix='NONE'
host=''
host_alias=''
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target=''
target_alias=''
target_cpu=''
target_os=''
target_vendor=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77
```

**Comment by remicollet** [comment]
>  cc: error: unrecognized command line option '-fstack-protector-strong'

So remove this one or use -fstack-protector or -fstack-protector-all instead

**Comment by andot** [comment]
OK, Thank you. it can be compiled now.

**Comment by andot** [comment]
I fixed all warning and note now, and I test pass with PHP 7.

**Comment by remicollet** [comment]
Seems much better.
Still some "-Wmaybe-uninitialized" warning with gcc 4.9 and only 1 segfault with hprose master and php adcf0c6052761350695da211b337edff12c6e63c (in tests/formatter.php)

```
 (gdb) bt
 #0  zend_mm_alloc_small (size=<optimized out>, bin_num=6, heap=0x7ffff3a00040) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_alloc.c:1232
 #1  zend_mm_alloc_heap (size=56, heap=0x7ffff3a00040) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_alloc.c:1299
 #2  _emalloc (size=size@entry=56) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_alloc.c:2208
 #3  0x000055555579f095 in zend_string_alloc (persistent=0, len=24) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_string.h:97
 #4  zend_unregister_functions (functions=<optimized out>, count=count@entry=-1, function_table=function_table@entry=0x0)
     at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_API.c:2453
 #5  0x00005555557a079c in module_destructor (module=module@entry=0x555555bd2c90) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_API.c:2530
 #6  0x000055555579764c in module_destructor_zval (zv=<optimized out>) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend.c:571
 #7  0x00005555557abee3 in _zend_hash_del_el_ex (prev=<optimized out>, p=0x555555b9d6f0, idx=18, ht=0x555555b902a0 <module_registry>)
     at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_hash.c:899
 #8  _zend_hash_del_el (p=0x555555b9d6f0, idx=18, ht=0x555555b902a0 <module_registry>) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_hash.c:923
 #9  zend_hash_graceful_reverse_destroy (ht=ht@entry=0x555555b902a0 <module_registry>) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_hash.c:1310
 #10 0x000055555579eaec in zend_destroy_modules () at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend_API.c:1993
 #11 0x0000555555798608 in zend_shutdown () at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/Zend/zend.c:802
 #12 0x000055555573b87b in php_module_shutdown () at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/main/main.c:2348
 #13 0x000055555561afb0 in main (argc=9, argv=0x555555b93cf0) at /usr/src/debug/php-src-adcf0c6052761350695da211b337edff12c6e63c/sapi/cli/php_cli.c:1349
```

Will try to dig more

**Comment by andot** [comment]
I fixed the last warning and segfault now. and I test pass with PHP 5.3-5.6, PHP 7.

**Comment by remicollet** [comment]
Remaining warning

```
/work/GIT/hprose-pecl/src/hprose_service.c:191:11: warning: '_aliases' may be used uninitialized in this function [-Wmaybe-uninitialized]
     zval *_aliases;
```

**Comment by andot** [comment]
OK, fixed it now.

**Comment by remicollet** [comment]
The build is clean now, thanks.

No more segfault in local build (still 1 in chrooted build, probably some race condition, so nothing you can do)

**Comment by andot** [comment]
Thank you! I released now.
